language: php

matrix:
  include:
    - php: 7.1
      env: TYPO3=dev-master
    - php: 7.1
      env: TYPO3=^8.0
    - php: 7.1
      env: TYPO3=^7.6.0
    - php: 7.0
      env: TYPO3=dev-master
    - php: 7.0
      env: TYPO3=^8.0
    - php: 7.0
      env: TYPO3=^7.6.0
    - php: 5.6
      env: TYPO3=^7.6.0
    - php: 5.5
      env: TYPO3=^7.6.0

addons:
  apt:
    packages:
      - parallel

cache:
  directories:
    - $HOME/.composer/cache

sudo: false

before_install:
  - if php -i | grep -q xdebug; then phpenv config-rm xdebug.ini; fi
  - composer self-update
  - composer --version

before_script:
  - composer require typo3/cms="$TYPO3"
  # Restore composer.json
  - git checkout composer.json
  - export TYPO3_PATH_WEB=$PWD/.Build/Web

script:
   - >
     echo;
     echo "Running unit tests";
     .Build/bin/phpunit -c .Build/vendor/typo3/cms/components/testing_framework/core/Build/UnitTests.xml Tests/Unit/
   - >
     echo;
     echo "Running php lint";
     find . -name \*.php ! -path "./.Build/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;
